name: Deploy Frontend to Azure Storage

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js (needed for some Azure Actions)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Upload Frontend to Azure Blob Storage
      run: |
        az storage blob upload-batch \
          -s ./frontend \
          -d '$web' \
          --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
