name: Deploy Frontend to Azure Storage

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js (needed for some Azure Actions)
      uses: actions/setup-node@v3
      with:
        node-version: '16'


    - name: Install and build
        run: |
          npm install
          npm run build

      # 4. Deploy to Azure Storage using access key
      - name: Deploy to Azure Storage
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
              --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
              --source ./build \
              --destination '$web'
