name: Deploy Frontend to Azure Storage

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js (needed for some Azure Actions)
      uses: actions/setup-node@v3
      with:
        node-version: '16'


    - name: Deploy to Azure Storage
        run:|
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
            --destination '$web' \
            --source ./build
