name: Deploy Frontend to Azure Storage

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js (needed for some Azure Actions)
      uses: actions/setup-node@v3
      with:
        node-version: '16'


    - name: 'Deploy to Azure Functions'
      uses: azure/functions-action@v1
      with:
        app-name: 'teami-func'
        slot-name: 'Production'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.Azure_Connection_STRING }}
