# .github/workflows/main_teami-func.yml
name: Build and deploy Python project to Azure Function App - teami-func

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # IMPORTANT: your Function code lives in backend/
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'
  PYTHON_VERSION: '3.12'
  AZURE_FUNCTIONAPP_NAME: 'teami-func'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Vendor deps into .python_packages for Functions on Linux Consumption
      - name: Install backend dependencies
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .python_packages/lib/site-packages

      # Zip ONLY the contents of backend/ so host.json sits at zip root
      - name: Create deployment package (zip)
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../release.zip . -x "venv/*" ".venv/*" "__pycache__/*"

      # Sanity check: confirm host.json/function_app.py are at the zip root
      - name: Inspect zip (sanity check)
        run: unzip -l release.zip | sed -n '1,200p'

      - name: Upload artifact for deploy
        uses: actions/upload-artifact@v4
        with:
          name: func-package
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write      # REQUIRED for OIDC login
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: func-package

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: release.zip
